#!/bin/bash
#Script auto create user SSH
clear
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (day): " Activetime

IP=$(wget -qO- ipv4.icanhazip.com);
useradd -e `date -d "$Activetime days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e "--------------------------------------"
echo -e "           Account Details"
echo -e "--------------------------------------"
echo -e "Host         : $IP"
echo -e "Username     : $Login"
echo -e "Password     : $Pass"
echo -e "Expiration   : $exp"
echo -e "Port OpenSSH : 22,444"
echo -e "Port Dropbear: 143,80,236"
echo -e "Port SSL     : 443,943"
echo -e "BadVPN UDPGW : 7200,7300,7600,7350"
echo -e "             : 7301,7302,7303"
echo -e "Squid Proxy  : 8000,8080,8989"
echo -e "OpenVPN TCP  : 1194"
echo -e "OpenVPN SSL  : 2905,9443"
echo -e "OpenVPN UDP  : 25000"
echo -e "Config http://$IP:81/myvpn-config.zip"
echo -e ""
echo -e "--------------------------------------"
echo -e ""
echo -e "---------------------------------------"
echo -e "    Terimakasih sudah menggunakan-"
echo -e "       Script Credit by Potato"
echo -e "---------------------------------------"
echo -e ""